# nginx.conf
server {
    listen 80;
    server_name localhost;

    location / {
        root /usr/share/nginx/html;
        index index.html index.htm;
        # Esta é a linha mágica que impede o erro 404:
        try_files $uri $uri/ /index.html;
    }
}